POST https://automatic-space-yodel-jj5qgvqv6x47frrg-8000.app.github.dev/train

###

GET https://automatic-space-yodel-jj5qgvqv6x47frrg-8000.app.github.dev/predict/left/0/right/0

###

GET https://automatic-space-yodel-jj5qgvqv6x47frrg-8000.app.github.dev/predict/left/1/right/0

###

POST https://automatic-space-yodel-jj5qgvqv6x47frrg-8000.app.github.dev/

### 